FROM alpine:3.14

# 安装 Node.js 和 npm
RUN apk add --no-cache nodejs npm

WORKDIR /app

COPY package*.json ./
RUN npm install --registry=https://registry.npmmirror.com

COPY . .

EXPOSE 3000

CMD ["node", "app.js"]
